import type { Metadata } from "next";
import dynamic from "next/dynamic";

import { Poppins } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/layout/AppLayout";

const ClientLayout = dynamic(() => import("@/components/layout/ClientLayout"));
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "OCR Image to Text",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={` ${poppins.className} antialiased`}
      >
        <ClientLayout>
          <AppLayout> {children}</AppLayout>
        </ClientLayout>
      </body>
    </html>
  );
}
